In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv('Sheet_1.csv')
df

,response_id,class,response_text,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,response_1,not_flagged,I try and avoid this sort of conflict,NaN,NaN,NaN,NaN,NaN
1,response_2,flagged,Had a friend open up to me about his mental ad...,NaN,NaN,NaN,NaN,NaN
2,response_3,flagged,I saved a girl from suicide once. She was goin...,NaN,NaN,NaN,NaN,NaN
3,response_4,not_flagged,i cant think of one really...i think i may hav...,NaN,NaN,NaN,NaN,NaN
4,response_5,not_flagged,Only really one friend who doesn't fit into th...,,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
75,response_76,not_flagged,"Now that I've been through it, although i'm no...",NaN,NaN,NaN,NaN,NaN
76,response_77,flagged,when my best friends mom past away from od'ing...,NaN,NaN,NaN,NaN,NaN
77,response_78,not_flagged,As a camp counselor I provide stability in kid...,NaN,NaN,NaN,NaN,NaN
78,response_79,flagged,My now girlfriend used to have serious addicti...,NaN,NaN,NaN,NaN,NaN
79,response_80,not_flagged,The one person I ever talked to it was because...,NaN,NaN,NaN,NaN,NaN

In [15]:
df.drop(columns=['response_id',	'Unnamed: 3','Unnamed: 4','Unnamed: 5'	,'Unnamed: 6'	,'Unnamed: 7'],inplace=True,axis=1)

In [16]:
df

          class                                      response_text
0   not_flagged              I try and avoid this sort of conflict
1       flagged  Had a friend open up to me about his mental ad...
2       flagged  I saved a girl from suicide once. She was goin...
3   not_flagged  i cant think of one really...i think i may hav...
4   not_flagged  Only really one friend who doesn't fit into th...
..          ...                                                ...
75  not_flagged  Now that I've been through it, although i'm no...
76      flagged  when my best friends mom past away from od'ing...
77  not_flagged  As a camp counselor I provide stability in kid...
78      flagged  My now girlfriend used to have serious addicti...
79  not_flagged  The one person I ever talked to it was because...

[80 rows x 2 columns]

In [17]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

In [ ]:
df['class'] = enc.fit_transform(df['class'])

In [19]:
df.head()

   class                                      response_text
0      1              I try and avoid this sort of conflict
1      0  Had a friend open up to me about his mental ad...
2      0  I saved a girl from suicide once. She was goin...
3      1  i cant think of one really...i think i may hav...
4      1  Only really one friend who doesn't fit into th...

In [22]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
import re