In [4]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv('market.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'market.csv'

In [ ]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Marketwise Price & Arrival Report (03-01-2026),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,Price (Rs./Quintal),NaN,NaN,Arrival (Metric Tonnes),NaN,NaN
1,Commodity Group,Commodity,MSP (Rs./Quintal) 2026-27,"Price on 03 Jan, 2026","Price on 02 Jan, 2026","Price on 01 Jan, 2026","Arrival on 03 Jan, 2026","Arrival on 02 Jan, 2026","Arrival on 01 Jan, 2026"
2,Cereals,Bajra(Pearl Millet/Cumbu),2775.00,2544.57,2624.36,2752.28,885.41,1485.92,1115.95
3,Cereals,Barley(Jau),1980.00,2449.90,2279.63,2311.48,24.36,280.06,164.82
4,Cereals,Jowar(Sorghum),3699.00,4785.34,4652.52,3316.88,178.01,285.48,726.42
5,Cereals,Maize,2400.00,1600.36,1653.55,1684.66,24752.68,39458.35,18306.48
6,Cereals,Paddy(Common),2369.00,2947.31,2616.04,2539.73,40886.97,117596.62,99107.28
7,Cereals,Ragi(Finger Millet),4886.00,5450.00,5500.00,5500.00,0.30,0.30,0.30
8,Cereals,Wheat,2425.00,2611.29,2607.51,2622.67,15319.49,27683.58,20537.98
9,Fibre Crops,Cotton,7710.00,7481.84,7506.77,7522.79,11370.30,18306.14,12667.79
10,Oil Seeds,Copra,12100.00,19766.36,19861.33,19921.02,10.70,12.98,17.98
11,Oil Seeds,Groundnut,7263.00,5840.79,6079.23,6149.29,3899.27,6553.59,6514.24
12,Oil Seeds,Mustard,5950.00,6534.16,6517.25,6608.16,865.44,1174.08,920.73
13,Oil Seeds,Niger Seed(Ramtil),9537.00,-,-,8290.32,-,-,12.40
14,Oil Seeds,Safflower,5940.00,7001.00,6600.00,6700.00,0.10,0.10,0.20
15,Oil Seeds,"Sesamum(Sesame,Gingelly,Til)",9846.00,9655.03,10482.29,10277.18,100.66,190.27,159.89
16,Oil Seeds,Soyabean,5328.00,4625.63,4568.68,4788.33,11579.40,12856.90,2871.24
17,Oil Seeds,Sunflower Seed,6760.00,-,5001.00,-,-,3.00,-
18,Pulses,Arhar(Tur/Red Gram)(Whole),8000.00,6790.15,6570.76,7166.90,430.72,527.21,603.84
19,Pulses,Bengal Gram(Gram)(Whole),5650.00,5363.28,5662.21,5827.63,966.06,1713.62,1108.11
20,Pulses,Black Gram(Urd Beans)(Whole),7800.00,6476.21,6708.74,7171.82,543.85,554.50,427.29
21,Pulses,Green Gram(Moong)(Whole),8768.00,6701.51,7296.73,6826.55,217.76,429.67,399.15
22,Pulses,Lentil(Masur)(Whole),6700.00,6602.17,7167.97,7560.30,288.02,557.66,328.70
23,Vegetables,Onion,-,1466.46,1499.99,1559.13,10556.62,16309.00,15066.17
24,Vegetables,Potato,-,760.12,754.51,743.11,49057.26,40034.53,36118.99
25,Vegetables,Tomato,-,3482.01,5585.77,3365.26,2524.75,9660.85,3442.78

In [ ]:
df.rename(columns={"Unnamed: 0": "Commodity Group", "Unnamed: 1": "Commodity","Unnamed: 3":"Price 0","Unnamed: 2":"Quantity","Unnamed: 5":"Price 2","Unnamed: 6":"Arrived Material 1","Unnamed: 7":"Arrival Material 2","Unnamed: 8":"Arrival Material 3","Marketwise Price & Arrival Report (03-01-2026)":"Price 1"}, inplace=True)
df.head()

,Commodity Group,Commodity,Quantity,Price 0,Price 1,Price 2,Arrived Material 1,Arrival Material 2,Arrival Material 3
0,NaN,NaN,NaN,Price (Rs./Quintal),NaN,NaN,Arrival (Metric Tonnes),NaN,NaN
1,Commodity Group,Commodity,MSP (Rs./Quintal) 2026-27,"Price on 03 Jan, 2026","Price on 02 Jan, 2026","Price on 01 Jan, 2026","Arrival on 03 Jan, 2026","Arrival on 02 Jan, 2026","Arrival on 01 Jan, 2026"
2,Cereals,Bajra(Pearl Millet/Cumbu),2775.00,2544.57,2624.36,2752.28,885.41,1485.92,1115.95
3,Cereals,Barley(Jau),1980.00,2449.90,2279.63,2311.48,24.36,280.06,164.82
4,Cereals,Jowar(Sorghum),3699.00,4785.34,4652.52,3316.88,178.01,285.48,726.42

In [ ]:
df.isna().sum()

Commodity Group       1
Commodity             1
Quantity              1
Price 0               0
Price 1               1
Price 2               1
Arrived Material 1    0
Arrival Material 2    1
Arrival Material 3    1
dtype: int64

In [ ]:
df.drop(0,inplace=True)
df.head()

,Commodity Group,Commodity,Quantity,Price 0,Price 1,Price 2,Arrived Material 1,Arrival Material 2,Arrival Material 3
1,Commodity Group,Commodity,MSP (Rs./Quintal) 2026-27,"Price on 03 Jan, 2026","Price on 02 Jan, 2026","Price on 01 Jan, 2026","Arrival on 03 Jan, 2026","Arrival on 02 Jan, 2026","Arrival on 01 Jan, 2026"
2,Cereals,Bajra(Pearl Millet/Cumbu),2775.00,2544.57,2624.36,2752.28,885.41,1485.92,1115.95
3,Cereals,Barley(Jau),1980.00,2449.90,2279.63,2311.48,24.36,280.06,164.82
4,Cereals,Jowar(Sorghum),3699.00,4785.34,4652.52,3316.88,178.01,285.48,726.42
5,Cereals,Maize,2400.00,1600.36,1653.55,1684.66,24752.68,39458.35,18306.48

In [ ]:
df.drop(1,inplace=True)
df.head()

,Commodity Group,Commodity,Quantity,Price 0,Price 1,Price 2,Arrived Material 1,Arrival Material 2,Arrival Material 3
2,Cereals,Bajra(Pearl Millet/Cumbu),2775.00,2544.57,2624.36,2752.28,885.41,1485.92,1115.95
3,Cereals,Barley(Jau),1980.00,2449.90,2279.63,2311.48,24.36,280.06,164.82
4,Cereals,Jowar(Sorghum),3699.00,4785.34,4652.52,3316.88,178.01,285.48,726.42
5,Cereals,Maize,2400.00,1600.36,1653.55,1684.66,24752.68,39458.35,18306.48
6,Cereals,Paddy(Common),2369.00,2947.31,2616.04,2539.73,40886.97,117596.62,99107.28

In [ ]:
df.reset_index(drop=True)

,Commodity Group,Commodity,Quantity,Price 0,Price 1,Price 2,Arrived Material 1,Arrival Material 2,Arrival Material 3
0,Cereals,Bajra(Pearl Millet/Cumbu),2775.00,2544.57,2624.36,2752.28,885.41,1485.92,1115.95
1,Cereals,Barley(Jau),1980.00,2449.90,2279.63,2311.48,24.36,280.06,164.82
2,Cereals,Jowar(Sorghum),3699.00,4785.34,4652.52,3316.88,178.01,285.48,726.42
3,Cereals,Maize,2400.00,1600.36,1653.55,1684.66,24752.68,39458.35,18306.48
4,Cereals,Paddy(Common),2369.00,2947.31,2616.04,2539.73,40886.97,117596.62,99107.28
5,Cereals,Ragi(Finger Millet),4886.00,5450.00,5500.00,5500.00,0.30,0.30,0.30
6,Cereals,Wheat,2425.00,2611.29,2607.51,2622.67,15319.49,27683.58,20537.98
7,Fibre Crops,Cotton,7710.00,7481.84,7506.77,7522.79,11370.30,18306.14,12667.79
8,Oil Seeds,Copra,12100.00,19766.36,19861.33,19921.02,10.70,12.98,17.98
9,Oil Seeds,Groundnut,7263.00,5840.79,6079.23,6149.29,3899.27,6553.59,6514.24
10,Oil Seeds,Mustard,5950.00,6534.16,6517.25,6608.16,865.44,1174.08,920.73
11,Oil Seeds,Niger Seed(Ramtil),9537.00,-,-,8290.32,-,-,12.40
12,Oil Seeds,Safflower,5940.00,7001.00,6600.00,6700.00,0.10,0.10,0.20
13,Oil Seeds,"Sesamum(Sesame,Gingelly,Til)",9846.00,9655.03,10482.29,10277.18,100.66,190.27,159.89
14,Oil Seeds,Soyabean,5328.00,4625.63,4568.68,4788.33,11579.40,12856.90,2871.24
15,Oil Seeds,Sunflower Seed,6760.00,-,5001.00,-,-,3.00,-
16,Pulses,Arhar(Tur/Red Gram)(Whole),8000.00,6790.15,6570.76,7166.90,430.72,527.21,603.84
17,Pulses,Bengal Gram(Gram)(Whole),5650.00,5363.28,5662.21,5827.63,966.06,1713.62,1108.11
18,Pulses,Black Gram(Urd Beans)(Whole),7800.00,6476.21,6708.74,7171.82,543.85,554.50,427.29
19,Pulses,Green Gram(Moong)(Whole),8768.00,6701.51,7296.73,6826.55,217.76,429.67,399.15
20,Pulses,Lentil(Masur)(Whole),6700.00,6602.17,7167.97,7560.30,288.02,557.66,328.70
21,Vegetables,Onion,-,1466.46,1499.99,1559.13,10556.62,16309.00,15066.17
22,Vegetables,Potato,-,760.12,754.51,743.11,49057.26,40034.53,36118.99
23,Vegetables,Tomato,-,3482.01,5585.77,3365.26,2524.75,9660.85,3442.78

In [ ]:
cols = ["Arrived Material 1", "Arrival Material 2", "Arrival Material 3"]

df[cols] = df[cols].replace('-', 0)

In [ ]:
df['Total Arrival']=df["Arrived Material 1"].astype(float)+df["Arrival Material 2"].astype(float)+df["Arrival Material 3"].astype(float)
df.head(3)

,Commodity Group,Commodity,Quantity,Price 0,Price 1,Price 2,Arrived Material 1,Arrival Material 2,Arrival Material 3,Total Arrival
2,Cereals,Bajra(Pearl Millet/Cumbu),2775.00,2544.57,2624.36,2752.28,885.41,1485.92,1115.95,3487.28
3,Cereals,Barley(Jau),1980.00,2449.90,2279.63,2311.48,24.36,280.06,164.82,469.24
4,Cereals,Jowar(Sorghum),3699.00,4785.34,4652.52,3316.88,178.01,285.48,726.42,1189.91

In [ ]:
cols1 = ["Price 0", "Price 1", "Price 2","Quantity"]

df[cols1] = df[cols1].replace('-', 0)

In [ ]:
df

,Commodity Group,Commodity,Quantity,Price 0,Price 1,Price 2,Arrived Material 1,Arrival Material 2,Arrival Material 3,Total Arrival
2,Cereals,Bajra(Pearl Millet/Cumbu),2775.00,2544.57,2624.36,2752.28,885.41,1485.92,1115.95,3487.28
3,Cereals,Barley(Jau),1980.00,2449.90,2279.63,2311.48,24.36,280.06,164.82,469.24
4,Cereals,Jowar(Sorghum),3699.00,4785.34,4652.52,3316.88,178.01,285.48,726.42,1189.91
5,Cereals,Maize,2400.00,1600.36,1653.55,1684.66,24752.68,39458.35,18306.48,82517.51
6,Cereals,Paddy(Common),2369.00,2947.31,2616.04,2539.73,40886.97,117596.62,99107.28,257590.87
7,Cereals,Ragi(Finger Millet),4886.00,5450.00,5500.00,5500.00,0.30,0.30,0.30,0.90
8,Cereals,Wheat,2425.00,2611.29,2607.51,2622.67,15319.49,27683.58,20537.98,63541.05
9,Fibre Crops,Cotton,7710.00,7481.84,7506.77,7522.79,11370.30,18306.14,12667.79,42344.23
10,Oil Seeds,Copra,12100.00,19766.36,19861.33,19921.02,10.70,12.98,17.98,41.66
11,Oil Seeds,Groundnut,7263.00,5840.79,6079.23,6149.29,3899.27,6553.59,6514.24,16967.10
12,Oil Seeds,Mustard,5950.00,6534.16,6517.25,6608.16,865.44,1174.08,920.73,2960.25
13,Oil Seeds,Niger Seed(Ramtil),9537.00,0,0,8290.32,0,0,12.40,12.40
14,Oil Seeds,Safflower,5940.00,7001.00,6600.00,6700.00,0.10,0.10,0.20,0.40
15,Oil Seeds,"Sesamum(Sesame,Gingelly,Til)",9846.00,9655.03,10482.29,10277.18,100.66,190.27,159.89,450.82
16,Oil Seeds,Soyabean,5328.00,4625.63,4568.68,4788.33,11579.40,12856.90,2871.24,27307.54
17,Oil Seeds,Sunflower Seed,6760.00,0,5001.00,0,0,3.00,0,3.00
18,Pulses,Arhar(Tur/Red Gram)(Whole),8000.00,6790.15,6570.76,7166.90,430.72,527.21,603.84,1561.77
19,Pulses,Bengal Gram(Gram)(Whole),5650.00,5363.28,5662.21,5827.63,966.06,1713.62,1108.11,3787.79
20,Pulses,Black Gram(Urd Beans)(Whole),7800.00,6476.21,6708.74,7171.82,543.85,554.50,427.29,1525.64
21,Pulses,Green Gram(Moong)(Whole),8768.00,6701.51,7296.73,6826.55,217.76,429.67,399.15,1046.58
22,Pulses,Lentil(Masur)(Whole),6700.00,6602.17,7167.97,7560.30,288.02,557.66,328.70,1174.38
23,Vegetables,Onion,0,1466.46,1499.99,1559.13,10556.62,16309.00,15066.17,41931.79
24,Vegetables,Potato,0,760.12,754.51,743.11,49057.26,40034.53,36118.99,125210.78
25,Vegetables,Tomato,0,3482.01,5585.77,3365.26,2524.75,9660.85,3442.78,15628.38

In [ ]:

px.pie(df,names='Commodity',values='Quantity',title='Crops & Quantity')

In [ ]:
px.bar(df,x='Commodity',y='Price 1',color='Quantity',title='Price of Crops with Mentioned Quantity <03-Jan-2026>')

In [ ]:
px.funnel(df,x='Commodity',y='Price 2',title='Price on 01-Jan-2026',color='Commodity Group')

In [ ]:
px.scatter(df,x='Commodity',y='Price 0',color='Commodity Group',title='Price on 02-Jan-2026 Same Quantity')

In [ ]:
px.pie(df,names='Commodity Group',values='Quantity',title='Seeds & Quantity')

In [ ]:
px.line(df,x='Commodity',y='Total Arrival')

In [ ]:
df.to_csv('crops.csv')

NameError: name 'df' is not defined